
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('movies').del()
    .then(function () {
      // Inserts seed entries
      return knex('movies').insert([
        {id: 1, title: 'The Pursuit of Happyness', image: 'https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/thepursuitofhappyness_onesheet_1400x2100.png?itok=BSpvsOsJ', rating: '5', genre: 'Biography, Drama', plot: 'A struggling salesman takes custody of his son as he\'s poised to begin a life-changing professional career.', cast: 'Will Smith, Jaden Smith, Thandiwe Newton', releaseDate: '12/15/2006', language: 'English'},
        {id: 2, title: 'Inception', image: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg', rating: '5', genre: 'Action, Adventure, Sci-Fi', plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', cast: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page', releaseDate: '07/16/2010', language: 'English'},
        {id: 3, title: 'Friday', image: 'https://images-na.ssl-images-amazon.com/images/I/81tp9pYsWqL._RI_.jpg', rating: '4', genre: 'Comedy, Drama', plot: 'It\'s Friday, and Craig and Smokey must come up with $200 they owe a local bully or there won\'t be a Saturday.', cast: 'Ice Cube, Chris Tucker, Nia Long', releaseDate: '04/26/1995', language: 'English'},
          {id: 4, title: 'Seven Pounds', image: 'https://i.pinimg.com/originals/63/5a/a9/635aa9275accabb30f952da717c0e35b.jpg', rating: '4', genre: 'Drama', plot: 'A man with a fateful secret embarks on an extraordinary journey of redemption by forever changing the lives of seven strangers.', cast: 'Will Smith, Rosario Dawson, Woody Harrelson', releaseDate: '12/19/2008', language: 'English'},
          {id: 5, title: 'Training Day', image: 'https://flxt.tmsimg.com/assets/p28363_p_v10_ag.jpg', rating: '5', genre: 'Crime, Drama, Thriller', plot: 'A rookie cop spends his first day as a Los Angeles narcotics officer with a rogue detective who isn\'t what he appears to be.', cast: 'Denzel Washington, Ethan Hawke, Scott Glenn', releaseDate: '10/05/2001', language: 'English'},
          {id: 6, title: 'Fences', image: 'https://images-na.ssl-images-amazon.com/images/I/91rlSZKayHL._SL1500_.jpg', rating: '4', genre: 'Drama', plot: 'A working-class African-American father tries to raise his family in the 1950s, while coming to terms with the events of his life.', cast: 'Denzel Washington, Viola Davis, Stephen McKinley Henderson', releaseDate: '12/25/2016', language: 'English'},
          {id: 7, title: 'Tenet', image: 'https://m.media-amazon.com/images/M/MV5BYzg0NGM2NjAtNmIxOC00MDJmLTg5ZmYtYzM0MTE4NWE2NzlhXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', rating: '4', genre: 'Action, Sci-Fi, Thriller', plot: 'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.', cast: 'John David Washington, Robert Pattinson, Elizabeth Debicki', releaseDate: '09/03/2020', language: 'English'},
          {id: 8, title: 'Step Brothers', image: 'https://m.media-amazon.com/images/I/51oUqGb18cL._AC_.jpg', rating: '5', genre: 'Comedy', plot: 'Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry.', cast: 'Will Ferrell, John C. Reilly, Mary Steenburgen', releaseDate: '07/25/2008', language: 'English'},
          {id: 9, title: 'Django Unchained', image: 'https://images-na.ssl-images-amazon.com/images/I/81j%2B2aZnWhL._AC_SL1500_.jpg', rating: '4', genre: 'Drama, Western ', plot: 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.', cast: 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio', releaseDate: '12/25/2012', language: 'English'},
          {id: 10, title: 'The Hateful Eight', image: 'https://m.media-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_.jpg', rating: '3', genre: 'Crime, Drama, Mystery', plot: 'In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.', cast: 'Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh', releaseDate: '12/30/2015', language: 'English'},
          {id: 11, title: 'The Magnificent Seven', image: 'https://images-na.ssl-images-amazon.com/images/I/91DbulUMr%2BL._SL1500_.jpg', rating: '4', genre: 'Action, Adventure, Western', plot: 'Seven gunmen from a variety of backgrounds are brought together by a vengeful young widow to protect her town from the private army of a destructive industrialist.', cast: 'Denzel Washington, Chris Pratt, Ethan Hawke', releaseDate: '09/23/2016', language: 'English'},
          {id: 12, title: 'Shutter Island', image: 'https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg', rating: '3', genre: 'Mystery, Thriller', plot: 'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.', cast: 'Leonardo DiCaprio, Emily Mortimer, Mark Ruffalo', releaseDate: '02/19/2010', language: 'English'}
      ]);
    });
};
